[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps = 
	adafruit/Adafruit SSD1306
	adafruit/Adafruit GFX Library
	adafruit/Adafruit MPU6050
	adafruit/Adafruit Unified Sensor
	bblanchon/ArduinoJson
    Links2004/WebSockets
    olikraus/U8g2
    https://github.com/playfultechnology/esp32-eyes.git
	madhephaestus/ESP32Servo
	earlephilhower/ESP8266Audio @ 1.9.7 